# address you want the service to listen on
address: ":9000"

# the jwks path endpoint you wish to expose
jwks_uri: "/certs"

merge:
  - https://keycloak.asoorm.do.poc.tyk.technology/realms/master/protocol/openid-connect/certs
  - https://keycloak.asoorm.do.poc.tyk.technology/realms/asoorm/protocol/openid-connect/certs
