kind: Secret
apiVersion: v1
type:
  Opaque
metadata:
  name: merge-jwks-{{.Release.Name}}-secret
stringData:
  config.yaml: |
    address: ":{{ .Values.merger.containerPort }}"
    jwks_uri: "{{ .Values.merger.uri }}"
    merge:
{{ toYaml .Values.merger.jwksEndpoints | indent 6 }}