---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: httpbin-keycloak
spec:
  name: httpbin-keycloak
  state: active
  active: true
  access_rights_array:
    - name: httpbin-keycloak
      namespace: httpbin
      versions:
        - Default
---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin-keycloak
spec:
  name: httpbin-keycloak
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin-svc.httpbin.svc:8000
    listen_path: /httpbin-keycloak
    strip_listen_path: true
  enable_jwt: true
  jwt_signing_method: rsa
  jwt_source: http://keycloak-service.keycloak.svc:7000/realms/keycloak-oauth/protocol/openid-connect/certs
  jwt_identity_base_field: sub
  jwt_policy_field_name: pol
  jwt_default_policies:
    - httpbin/httpbin-keycloak
