---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: merge-jwks
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    path: chart
    repoURL: https://github.com/asoorm/merge-jwks
    targetRevision: update-helm
    helm:
      releaseName: merge-jwks
  destination:
    server: https://kubernetes.default.svc
    namespace: merge-jwks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
